name = "backend"
compatibility_date = "2024-08-25"

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWJlZjNiOTctMTQzNC00YzFkLWFhNGItODMxZGFmZGJmZjYyIiwidGVuYW50X2lkIjoiOGNmZjFlZDI0YzVlZTMzNjk0NWQ1YTgyMzFjNjQ3OWE1YWE3NzM5ODRmZDhkOTNiZmE0ODAzYTdmNzVkZWNjNiIsImludGVybmFsX3NlY3JldCI6ImY4NmQ5ZjEzLTIwY2QtNGY4OS05ZWQ0LTRjOWEyNDY2ZjA4MyJ9.MQV8cfkOBteRf7LsuiLV0LNJ9orb22LHuG16M5rOl6U"